ALTER TABLE contacts
DROP CONSTRAINT IF EXISTS contacts_pkey;

ALTER TABLE contacts
DROP COLUMN IF EXISTS user_id1;

ALTER TABLE contacts
ADD COLUMN id BIGSERIAL PRIMARY KEY;

ALTER TABLE contacts
ADD COLUMN user_id1 BIGSERIAL;

ALTER TABLE contacts
    ADD CONSTRAINT fk_user1 FOREIGN KEY (user_id1)
    REFERENCES users(id)
    ON DELETE CASCADE;

ALTER TABLE contacts
ADD COLUMN is_favourite BOOLEAN DEFAULT FALSE;
